---
title: 'CA2124: Anfällige finally-Klauseln mit äußerem try-Block umschließen.'
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: mikejo5000
ms.author: mikejo
manager: jillfra
ms.workload:
- multiple
ms.openlocfilehash: a0ad312a6a79240ca86fd6f9ca3b776e2ba8f3b0
ms.sourcegitcommit: a18c7e9b367c2f92f6e54c3eaef442775d457667
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/15/2020
ms.locfileid: "90098476"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124: Anfällige finally-Klauseln mit äußerem try-Block umschließen.

|Element|Wert|
|-|-|
|RuleId|CA2124|
|Category|Microsoft.Security|
|Unterbrechende Änderung|Nicht unterbrechend|

## <a name="cause"></a>Ursache
In den Versionen 1,0 und 1,1 des .NET Framework enthält eine öffentliche oder geschützte Methode einen- `try` / `catch` / `finally` Block. Der `finally` -Block scheint den Sicherheitszustand zurückzusetzen und ist nicht in einen- `finally` Block eingeschlossen.

> [!NOTE]
> Diese Regel wurde als veraltet markiert. Weitere Informationen finden Sie unter [Veraltete Regeln](fxcop-unported-deprecated-rules.md).

## <a name="rule-description"></a>Regelbeschreibung
Diese Regel `try` / `finally` findet Blöcke im Code, die auf die Versionen 1,0 und 1,1 des .NET Framework ausgerichtet sind, die anfällig für schädliche Ausnahme Filter in der-Aufrufe sind. Wenn sensible Vorgänge wie der Identitätswechsel im try-Block auftreten und eine Ausnahme ausgelöst wird, kann der Filter vor dem-Block ausgeführt werden `finally` . Für das Beispiel für den Identitätswechsel bedeutet dies, dass der Filter als Benutzer mit Identitätswechsel ausgeführt wird. Filter sind zurzeit nur in Visual Basic implementierbar.

> [!NOTE]
> In den Versionen 2,0 und höher des .NET Framework schützt die Common Language Runtime automatisch einen- `try` / `catch` /  `finally` Block vor bösartigen Ausnahme filtern, wenn die zurück Setzung direkt innerhalb der Methode auftritt, die den Ausnahme Block enthält.

## <a name="how-to-fix-violations"></a>Behandeln von Verstößen
Fügen Sie den nicht umschließenen `try` / `finally` in einen äußeren try-Block ein. Siehe das zweite Beispiel, das folgt. Dadurch wird erzwungen `finally` , dass vor dem Filtern von Code ausgeführt wird.

## <a name="when-to-suppress-warnings"></a>Wann sollten Warnungen unterdrückt werden?
Unterdrücken Sie keine Warnung dieser Regel.

## <a name="pseudo-code-example"></a>Pseudo Codebeispiel

### <a name="description"></a>BESCHREIBUNG

Der folgende Pseudocode veranschaulicht das von dieser Regel erkannte Muster.

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

Der folgende Pseudo Code zeigt das Muster, das Sie verwenden können, um Ihren Code zu schützen und diese Regel zu erfüllen.

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```
